In [15]:
from functions import *

results_df = pd.read_pickle("results.pkl")
cnn_results = results_df.groupby(results_df["model"]).agg([np.mean, np.std])
cnn_results.to_csv("results_summary.csv")

cnn_results

                                 accuracy           precision            \
                                     mean       std      mean       std
model
Ghana_CNN_Manuscript             0.947638  0.010285  0.595140  0.096751
Ghana_CNN_cnn_train.py           0.946850  0.011562  0.586980  0.103760
Ghana_CNN_rep_settings.py        0.948819  0.011893  0.603095  0.111625
Philippines_CNN_Manuscript       0.952263  0.012033  0.525463  0.188170
Philippines_CNN_cnn_train.py     0.949794  0.012567  0.487839  0.136524
Philippines_CNN_rep_settings.py  0.946091  0.011856  0.446203  0.111687
Venezuela_CNN_Manuscript         0.942790  0.004010  0.468296  0.069010
Venezuela_CNN_cnn_train.py       0.937163  0.007803  0.429909  0.055051
Venezuela_CNN_rep_settings.py    0.928253  0.006058  0.368280  0.021410

                                   recall                  f1
                                     mean       std      mean       std
model
Ghana_CNN_Manuscript             0.537500  0.119814  0.560641  0.100524
Ghana_CNN_cnn_train.py           0.600000  0.026146  0.590579  0.060664
Ghana_CNN_rep_settings.py        0.593750  0.058463  0.596324  0.078087
Philippines_CNN_Manuscript       0.443478  0.120647  0.468804  0.110474
Philippines_CNN_cnn_train.py     0.469565  0.071442  0.474601  0.093384
Philippines_CNN_rep_settings.py  0.434783  0.053250  0.437534  0.076845
Venezuela_CNN_Manuscript         0.268085  0.048982  0.339502  0.051539
Venezuela_CNN_cnn_train.py       0.382979  0.049898  0.401825  0.038726
Venezuela_CNN_rep_settings.py    0.412766  0.099341  0.383916  0.040497

In [13]:

vz3 = results_df.iloc[:9]
vz3.groupby(results_df["model"]).agg([np.mean, np.std])

                               accuracy           precision            \
                                   mean       std      mean       std
model
Venezuela_CNN_Manuscript       0.940602  0.003582  0.432009  0.063799
Venezuela_CNN_cnn_train.py     0.934740  0.009548  0.409974  0.061541
Venezuela_CNN_rep_settings.py  0.928097  0.004881  0.358509  0.009079

                                 recall                  f1
                                   mean       std      mean       std
model
Venezuela_CNN_Manuscript       0.262411  0.065001  0.325450  0.066403
Venezuela_CNN_cnn_train.py     0.361702  0.056293  0.378999  0.026532
Venezuela_CNN_rep_settings.py  0.382979  0.085106  0.366860  0.037871

In [11]:
gh3 = results_df.iloc[15:24]
gh3.groupby(results_df["model"]).agg([np.mean, np.std])

                           accuracy           precision              recall  \
                               mean       std      mean       std      mean
model
Ghana_CNN_Manuscript       0.950787  0.011811  0.620105  0.114263  0.614583
Ghana_CNN_cnn_train.py     0.951444  0.011866  0.626418  0.113620  0.614583
Ghana_CNN_rep_settings.py  0.952100  0.014775  0.637037  0.138926  0.614583

                                           f1
                                std      mean       std
model
Ghana_CNN_Manuscript       0.018042  0.614692  0.063624
Ghana_CNN_cnn_train.py     0.018042  0.617897  0.063917
Ghana_CNN_rep_settings.py  0.036084  0.622542  0.084915

In [12]:
ph3 = results_df.iloc[30:39]
ph3.groupby(results_df["model"]).agg([np.mean, np.std])

                                 accuracy           precision            \
                                     mean       std      mean       std
model
Philippines_CNN_Manuscript       0.945130  0.007790  0.417438  0.076084
Philippines_CNN_cnn_train.py     0.941701  0.008316  0.397379  0.077703
Philippines_CNN_rep_settings.py  0.938957  0.009504  0.375153  0.077522

                                   recall                  f1
                                     mean       std      mean       std
model
Philippines_CNN_Manuscript       0.405797  0.139763  0.406467  0.098759
Philippines_CNN_cnn_train.py     0.449275  0.090507  0.421621  0.083060
Philippines_CNN_rep_settings.py  0.420290  0.066414  0.396079  0.072277